/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.util.Calendar;
import java.util.Date;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class AnhadirEmpleados extends javax.swing.JFrame {

    private proyectobasesdatos.ProyectoBasesDatos pr;
    private MenuEmpleados padre;

    

    public AnhadirEmpleados(proyectobasesdatos.ProyectoBasesDatos pr) {
        this.pr = pr;

        initComponents();
        anhadir.setEnabled(false);
        aviso.setVisible(false);
        avisoDNI.setVisible(false);
        avisoFecha.setVisible(false);
        avisoTel.setVisible(false);
        jComboBoxAtraccion.setEnabled(false);
        jComboBoxEspectaculo.setEnabled(false);
        jComboBoxRestaurante.setEnabled(false);
        asignarAutom.setEnabled(false);
    }

    public AnhadirEmpleados(proyectobasesdatos.ProyectoBasesDatos pr, MenuEmpleados padre) {
        this.pr = pr;
        this.padre = padre;
        initComponents();
        anhadir.setEnabled(false);
        aviso.setVisible(false);
        avisoDNI.setVisible(false);
        avisoFecha.setVisible(false);
        avisoTel.setVisible(false);
        jComboBoxAtraccion.setEnabled(false);
        jComboBoxEspectaculo.setEnabled(false);
        jComboBoxRestaurante.setEnabled(false);
        asignarAutom.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        dni = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        direccion = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        fechaNacimiento = new com.toedter.calendar.JDateChooser();
        atraccion = new javax.swing.JLabel();
        String[] array = pr.getAtraccionesDAO().atraccionesActivas().toArray(new String[pr.getAtraccionesDAO().atraccionesActivas().size()]);
        jComboBoxAtraccion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        String[] array2 = pr.getEspectaculosDAO().espectaculosActivos().toArray(new String[pr.getEspectaculosDAO().espectaculosActivos().size()]);
        jComboBoxEspectaculo = new javax.swing.JComboBox<>();
        trabajadorAtra = new javax.swing.JRadioButton();
        trabajadorEsp = new javax.swing.JRadioButton();
        Hostelero = new javax.swing.JRadioButton();
        anhadir = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        String[] array3 = pr.getHosteleriaDAO().establecimientosActivos().toArray(new String[pr.getHosteleriaDAO().establecimientosActivos().size()]);
        jComboBoxRestaurante = new javax.swing.JComboBox<>();
        telefono = new javax.swing.JTextField();
        aviso = new javax.swing.JLabel();
        avisoDNI = new javax.swing.JLabel();
        avisoTel = new javax.swing.JLabel();
        avisoFecha = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        salario = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        asignarAutom = new javax.swing.JCheckBox();
        admin = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setLabelFor(dni);
        jLabel1.setText("DNI:");

        jLabel2.setText("Nombre:");

        jLabel3.setText("Dirección:");

        jLabel4.setText("Teléfono:");

        jLabel5.setText("Fecha de Nacimiento:");

        atraccion.setText("Atracción:");

        jComboBoxAtraccion.setModel(new javax.swing.DefaultComboBoxModel<>(array));
        jComboBoxAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAtraccionActionPerformed(evt);
            }
        });

        jLabel7.setText("Espectáculo:");

        jComboBoxEspectaculo.setModel(new javax.swing.DefaultComboBoxModel<>(array2));

        trabajadorAtra.setText("Trabajador Atracción");
        trabajadorAtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadorAtraActionPerformed(evt);
            }
        });

        trabajadorEsp.setText("Trabajador Espectáculo");
        trabajadorEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadorEspActionPerformed(evt);
            }
        });

        Hostelero.setText("Hostelero");
        Hostelero.setActionCommand("Administrador");
        Hostelero.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HosteleroActionPerformed(evt);
            }
        });

        anhadir.setText("Añadir");
        anhadir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                anhadirActionPerformed(evt);
            }
        });

        atras.setText("Atrás");
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });

        jLabel8.setText("Restaurante:");

        jComboBoxRestaurante.setModel(new javax.swing.DefaultComboBoxModel<>(array3));

        telefono.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                telefonoActionPerformed(evt);
            }
        });

        aviso.setForeground(new java.awt.Color(255, 51, 51));
        aviso.setText("Todos los campos son obligatorios");

        avisoDNI.setForeground(new java.awt.Color(255, 51, 51));
        avisoDNI.setText("Formato DNI incorrecto");

        avisoTel.setForeground(new java.awt.Color(255, 51, 51));
        avisoTel.setText("Fomato de teléfono incorrecto");

        avisoFecha.setForeground(new java.awt.Color(255, 51, 51));
        avisoFecha.setText("Fecha de nacimiento incorrecta");

        jLabel9.setText("Salario:");

        salario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                salarioActionPerformed(evt);
            }
        });

        jLabel10.setText("€");

        asignarAutom.setText("Asignar automático");
        asignarAutom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                asignarAutomActionPerformed(evt);
            }
        });

        admin.setText("Administrador");
        admin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adminActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(avisoDNI)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel2)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 323, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jLabel9)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(avisoTel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(avisoFecha)))
                        .addGap(0, 79, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(anhadir)
                .addGap(75, 75, 75))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(trabajadorAtra)
                        .addGap(18, 18, 18)
                        .addComponent(trabajadorEsp)
                        .addGap(26, 26, 26)
                        .addComponent(Hostelero)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(admin))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(atraccion)
                            .addComponent(jLabel8))
                        .addGap(29, 29, 29)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBoxAtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBoxRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, 184, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(asignarAutom)))
                .addGap(49, 49, 49))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(aviso)
                .addGap(225, 225, 225))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(avisoDNI)
                .addGap(5, 5, 5)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(dni, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(avisoTel)
                    .addComponent(avisoFecha))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel4)
                        .addComponent(telefono, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5))
                    .addComponent(fechaNacimiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(7, 7, 7)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(trabajadorEsp)
                    .addComponent(trabajadorAtra)
                    .addComponent(Hostelero)
                    .addComponent(admin))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBoxAtraccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(atraccion)
                    .addComponent(asignarAutom))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jComboBoxEspectaculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jComboBoxRestaurante, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(aviso)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(atras)
                    .addComponent(anhadir))
                .addGap(19, 19, 19))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void trabajadorAtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadorAtraActionPerformed
        if (trabajadorAtra.isSelected()) {
            admin.setEnabled(false);
            Hostelero.setEnabled(false);
            jComboBoxAtraccion.setEnabled(true);
            asignarAutom.setEnabled(true);
            anhadir.setEnabled(true);
        } else {
            jComboBoxAtraccion.setEnabled(false);
            admin.setEnabled(true);
            Hostelero.setEnabled(true);
            asignarAutom.setEnabled(false);
            if (!trabajadorEsp.isSelected() && !Hostelero.isSelected() && !admin.isSelected()) {
                anhadir.setEnabled(false);
            }
        }

    }//GEN-LAST:event_trabajadorAtraActionPerformed

    private void trabajadorEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadorEspActionPerformed
        if (trabajadorEsp.isSelected()) {
            admin.setEnabled(false);
            Hostelero.setEnabled(false);
            jComboBoxEspectaculo.setEnabled(true);
            anhadir.setEnabled(true);
        } else {
            jComboBoxEspectaculo.setEnabled(false);
            admin.setEnabled(true);
            Hostelero.setEnabled(true);
            if (!trabajadorAtra.isSelected() && !Hostelero.isSelected() && !admin.isSelected()) {
                anhadir.setEnabled(false);
            }
        }
    }//GEN-LAST:event_trabajadorEspActionPerformed

    private void HosteleroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HosteleroActionPerformed
        if (Hostelero.isSelected()) {
            admin.setEnabled(false);
            asignarAutom.setEnabled(false);
            trabajadorAtra.setEnabled(false);
            trabajadorEsp.setEnabled(false);
            jComboBoxRestaurante.setEnabled(true);
            jComboBoxAtraccion.setEnabled(false);
            jComboBoxEspectaculo.setEnabled(false);
            anhadir.setEnabled(true);
        } else {
            jComboBoxRestaurante.setEnabled(false);
            admin.setEnabled(true);
            trabajadorAtra.setEnabled(true);
            trabajadorEsp.setEnabled(true);
            if (!trabajadorAtra.isSelected() && !trabajadorEsp.isSelected() && !admin.isSelected()) {
                anhadir.setEnabled(false);
            }
        }
    }//GEN-LAST:event_HosteleroActionPerformed

    private void anhadirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_anhadirActionPerformed
        int error = 0;
        aviso.setVisible(false);
        avisoDNI.setVisible(false);
        avisoFecha.setVisible(false);
        avisoTel.setVisible(false);
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 1);

        cal.add(Calendar.YEAR, -16);
        Date fecha = cal.getTime();
        if (!dni.getText().isBlank() && !salario.getText().isBlank() && !nombre.getText().isBlank() && !direccion.getText().isBlank() && !telefono.getText().isBlank() && !fechaNacimiento.getDate().toString().isBlank()) {
            if (dni.getText().length() != 9) {
                avisoDNI.setVisible(true);
                error = 1;
            }
            if (telefono.getText().length() != 9) {
                avisoTel.setVisible(true);
                error = 1;
            }
            if (!fechaNacimiento.getDate().before(fecha)) {
                avisoFecha.setVisible(true);
                error = 1;
            }
            if (error == 0) {
                try {
                    anhadirEmpleado();
                } catch (SQLException ex) {
                    Logger.getLogger(AnhadirEmpleados.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        } else
            aviso.setVisible(true);
    }//GEN-LAST:event_anhadirActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void telefonoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_telefonoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_telefonoActionPerformed

    private void salarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_salarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_salarioActionPerformed

    private void asignarAutomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_asignarAutomActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_asignarAutomActionPerformed

    private void jComboBoxAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAtraccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxAtraccionActionPerformed

    private void adminActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adminActionPerformed
        // TODO add your handling code here:
        if(admin.isSelected()){
            trabajadorAtra.setEnabled(false);
            trabajadorEsp.setEnabled(false);
            anhadir.setEnabled(true);
            Hostelero.setEnabled(false);
        }    
        else{
            anhadir.setEnabled(false);
            trabajadorAtra.setEnabled(true);
            trabajadorEsp.setEnabled(true);
            Hostelero.setEnabled(true);
        }
    }//GEN-LAST:event_adminActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Hostelero;
    private javax.swing.JRadioButton admin;
    private javax.swing.JButton anhadir;
    private javax.swing.JCheckBox asignarAutom;
    private javax.swing.JLabel atraccion;
    private javax.swing.JButton atras;
    private javax.swing.JLabel aviso;
    private javax.swing.JLabel avisoDNI;
    private javax.swing.JLabel avisoFecha;
    private javax.swing.JLabel avisoTel;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField dni;
    private com.toedter.calendar.JDateChooser fechaNacimiento;
    private javax.swing.JComboBox<String> jComboBoxAtraccion;
    private javax.swing.JComboBox<String> jComboBoxEspectaculo;
    private javax.swing.JComboBox<String> jComboBoxRestaurante;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField salario;
    private javax.swing.JTextField telefono;
    private javax.swing.JRadioButton trabajadorAtra;
    private javax.swing.JRadioButton trabajadorEsp;
    // End of variables declaration//GEN-END:variables

    public void anhadirEmpleado() throws SQLException {
        Calendar cal = Calendar.getInstance();
        cal.set(Calendar.HOUR_OF_DAY, 0);
        cal.set(Calendar.MINUTE, 0);
        cal.set(Calendar.SECOND, 0);
        cal.set(Calendar.MILLISECOND, 1);
        Date hoy = cal.getTime();
        
        Date nacimiento = fechaNacimiento.getDate();
        java.sql.Date nacimiento2 = new java.sql.Date(nacimiento.getTime());
        Float sueldo = Float.parseFloat(salario.getText());
        if (!Hostelero.isSelected()) {
            if (trabajadorAtra.isSelected() && trabajadorEsp.isSelected()) {
                
                if(asignarAutom.isSelected()){
                    String atraccion=pr.getTrabajadoresDAO().getAtraccionMenosTrabajadores();
                    
                    pr.getTrabajadoresDAO().anhadirTrabajadorAtraEsp(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(),  nacimiento2, atraccion, jComboBoxEspectaculo.getSelectedItem().toString(), sueldo);
                
                }else{
                   
                    pr.getTrabajadoresDAO().anhadirTrabajadorAtraEsp(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(), nacimiento2, jComboBoxAtraccion.getSelectedItem().toString(), jComboBoxEspectaculo.getSelectedItem().toString(), sueldo);
                }
                
            } else if (trabajadorAtra.isSelected() && !trabajadorEsp.isSelected()) {
                if(asignarAutom.isSelected()){
                    String atraccion=pr.getTrabajadoresDAO().getAtraccionMenosTrabajadores();
                    pr.getTrabajadoresDAO().anhadirTrabajadorAtra(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(),  nacimiento2, atraccion, sueldo);
                    
                
                }else{
                    pr.getTrabajadoresDAO().anhadirTrabajadorAtra(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(),  nacimiento2, jComboBoxAtraccion.getSelectedItem().toString(), sueldo);
                }
                
            } else if (!trabajadorAtra.isSelected() && trabajadorEsp.isSelected()) {
                pr.getTrabajadoresDAO().anhadirTrabajadorEsp(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(), nacimiento2, jComboBoxEspectaculo.getSelectedItem().toString(), sueldo);

            } else if (admin.isSelected()){
                String clave = pr.getTrabajadoresDAO().AnhadirAdmin(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(),  nacimiento2, sueldo);
                //pr.getTrabajadoresDAO().anhadirTrabajador(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(),  nacimiento2, sueldo);
                if(clave!=null)
                    JOptionPane.showMessageDialog(rootPane, "La clave de este administrador es: " + clave);                
            }
            JOptionPane.showMessageDialog(rootPane, "Trabajador añadido");
        } else {
            pr.getHostelerosDAO().anhadirHostelero(dni.getText(), nombre.getText(), direccion.getText(), telefono.getText(),  nacimiento2, jComboBoxRestaurante.getSelectedItem().toString(),sueldo);
            JOptionPane.showMessageDialog(rootPane, "Hostelero añadido");
        }
    }
}
