/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class CambiarContraseña extends javax.swing.JFrame {

    private proyectobasesdatos.ProyectoBasesDatos pr;
    private Acceso padre;
     
    public CambiarContraseña(proyectobasesdatos.ProyectoBasesDatos pr, Acceso padre) {
        this.pr = pr;
        this.padre = padre;
        initComponents();
        etiquetaFallo1.setVisible(false);
        etiquetaFallo2.setVisible(false);
        etiquetaFallo3.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        DNI_Label = new javax.swing.JLabel();
        DNI = new javax.swing.JTextField();
        ContraseñaActual_Label = new javax.swing.JLabel();
        cambiar = new javax.swing.JButton();
        Atrás = new javax.swing.JButton();
        etiquetaFallo2 = new javax.swing.JLabel();
        etiquetaFallo1 = new javax.swing.JLabel();
        ContraseñaActual = new javax.swing.JPasswordField();
        ContraseñaNueva_Label = new javax.swing.JLabel();
        CambiarContraseña = new javax.swing.JLabel();
        ContraseñaNueva = new javax.swing.JPasswordField();
        etiquetaFallo3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        DNI_Label.setText("DNI");
        getContentPane().add(DNI_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 90, -1, -1));

        DNI.setForeground(new java.awt.Color(204, 204, 204));
        DNI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DNIActionPerformed(evt);
            }
        });
        getContentPane().add(DNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 90, 247, -1));

        ContraseñaActual_Label.setText("Contraseña Actual");
        getContentPane().add(ContraseñaActual_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, -1, -1));

        cambiar.setText("Cambiar");
        cambiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cambiarActionPerformed(evt);
            }
        });
        getContentPane().add(cambiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 290, -1, -1));

        Atrás.setText("Atrás");
        Atrás.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrásActionPerformed(evt);
            }
        });
        getContentPane().add(Atrás, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 290, -1, -1));

        etiquetaFallo2.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaFallo2.setText("Usuario o contraseña actual incorrectos");
        getContentPane().add(etiquetaFallo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, -1, -1));

        etiquetaFallo1.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaFallo1.setText("Todos los campos son obligatorios");
        getContentPane().add(etiquetaFallo1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, -1, -1));
        getContentPane().add(ContraseñaActual, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 140, 247, -1));

        ContraseñaNueva_Label.setText("Constraseña Nueva");
        getContentPane().add(ContraseñaNueva_Label, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        CambiarContraseña.setText("Cambiar Contraseña");
        getContentPane().add(CambiarContraseña, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 30, -1, -1));

        ContraseñaNueva.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ContraseñaNuevaActionPerformed(evt);
            }
        });
        getContentPane().add(ContraseñaNueva, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 190, 250, -1));

        etiquetaFallo3.setForeground(new java.awt.Color(255, 0, 0));
        etiquetaFallo3.setText("Máximo 8 caracteres");
        getContentPane().add(etiquetaFallo3, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 220, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AtrásActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrásActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_AtrásActionPerformed

    private void DNIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DNIActionPerformed

    }//GEN-LAST:event_DNIActionPerformed

    private void cambiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cambiarActionPerformed
        String dni=DNI.getText();
        String contrActual=ContraseñaActual.getText();
        String contrNueva=ContraseñaNueva.getText();
        if(!dni.isBlank() && !contrActual.isBlank() && !contrNueva.isBlank()){
            if (pr.getDaoUsuarios().validarUsuario(dni,contrActual,"Administrador")) {
                if(contrNueva.length()<=8){
                    if(pr.getDaoUsuarios().cambiarContraseña(dni,contrActual)){
                        JOptionPane.showMessageDialog(rootPane, "Se ha cambiado la contraseña");
                        MenuAdministradores ma = new MenuAdministradores(pr,padre.getPadreAdministradores());
                        this.setVisible(false);
                        ma.setVisible(true);
                    }
                    else{
                        JOptionPane.showMessageDialog(rootPane, "No se ha podido cambiar la contraseña");
                        etiquetaFallo1.setVisible(false);
                        etiquetaFallo2.setVisible(false);
                        etiquetaFallo3.setVisible(false);
                    }
                }
                else{
                    etiquetaFallo1.setVisible(false);
                    etiquetaFallo2.setVisible(false);
                    etiquetaFallo3.setVisible(true);
                }
            }
            else{
                etiquetaFallo1.setVisible(false);
                etiquetaFallo2.setVisible(true);
                etiquetaFallo3.setVisible(false);
            }
            
        }
        else{
            etiquetaFallo1.setVisible(true);
            etiquetaFallo2.setVisible(false);
            etiquetaFallo3.setVisible(false);
        }
        
    }//GEN-LAST:event_cambiarActionPerformed

    private void ContraseñaNuevaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ContraseñaNuevaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ContraseñaNuevaActionPerformed
    
    /**
     * @param args the command line arguments
     */
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atrás;
    private javax.swing.JLabel CambiarContraseña;
    private javax.swing.JPasswordField ContraseñaActual;
    private javax.swing.JLabel ContraseñaActual_Label;
    private javax.swing.JPasswordField ContraseñaNueva;
    private javax.swing.JLabel ContraseñaNueva_Label;
    private javax.swing.JTextField DNI;
    private javax.swing.JLabel DNI_Label;
    private javax.swing.JButton cambiar;
    private javax.swing.JLabel etiquetaFallo1;
    private javax.swing.JLabel etiquetaFallo2;
    private javax.swing.JLabel etiquetaFallo3;
    // End of variables declaration//GEN-END:variables
}
