
package GUI;

import javax.swing.JSlider;
 import java.sql.Date;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.SwingConstants;

/**
 *
 * @author alumnogreibd
 */
public class E1_Puntuar extends javax.swing.JFrame {
    private proyectobasesdatos.ProyectoBasesDatos pr;
    private E1 padre;
    private Date fecha;
    private String dni;
    private String nombreEstablecimiento;

    /**
     * Creates new form E1_Puntuar
     */
    public E1_Puntuar(proyectobasesdatos.ProyectoBasesDatos pr, E1 padre, Date fecha, String dni, String nombreEstablecimiento) {
        this.pr = pr;
        this.padre = padre;
        this.fecha = fecha;
        this.dni = dni;
        this.nombreEstablecimiento = nombreEstablecimiento;
        initComponents();
        //JLabel Titulo2 = new JLabel("Valore la experiencia en " + nombreEstablecimiento + " en la fecha " + fecha.toString(), SwingConstants.CENTER);
        Titulo.setText("Valore la experiencia en " + nombreEstablecimiento + " en la fecha " + fecha.toString());
        Titulo.setHorizontalAlignment(SwingConstants.CENTER);
        Titulo.setVerticalAlignment(SwingConstants.CENTER);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Puntuar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        jRatingPuntuar = new de.sciss.rating.j.JRating();
        InfoSeleccion = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Puntuar.setText("Puntuar");
        Puntuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntuarActionPerformed(evt);
            }
        });

        Titulo.setText("Titulo (dinámico)");

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        jRatingPuntuar.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jRatingPuntuar.setForeground(new java.awt.Color(102, 102, 102));
        jRatingPuntuar.setGap(10);
        jRatingPuntuar.setMaxCount(10);
        jRatingPuntuar.setName(""); // NOI18N
        jRatingPuntuar.setOpaque(true);

        InfoSeleccion.setText("¿Problemas para seleccionar?");
        InfoSeleccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoSeleccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 236, Short.MAX_VALUE)
                .addComponent(Puntuar)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(132, 132, 132)
                        .addComponent(jRatingPuntuar, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(149, 149, 149)
                        .addComponent(InfoSeleccion))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(Titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addComponent(Titulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 29, Short.MAX_VALUE)
                .addComponent(InfoSeleccion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jRatingPuntuar, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puntuar)
                    .addComponent(Atras))
                .addGap(44, 44, 44))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void PuntuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntuarActionPerformed
                
        pr.getComerDAO().puntuar(fecha, dni, nombreEstablecimiento, jRatingPuntuar.getMarkedCount());
        padre.buscarEvaluacionesPendientes(); //Actualizo para que ya no aparezca la comida actual como pendiente de evaluar
        JOptionPane.showMessageDialog(rootPane, "Valoración guardada\n¡Gracias por su tiempo!");
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_PuntuarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void InfoSeleccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoSeleccionActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Para seleccionar un número determinado de estrellas debe clicar en la parte derecha de la estrella posicionada más a la derecha"
                + "\nTambién puede arrastrar hasta llegar a la puntuación deseada");
    }//GEN-LAST:event_InfoSeleccionActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton InfoSeleccion;
    private javax.swing.JButton Puntuar;
    private javax.swing.JLabel Titulo;
    private de.sciss.rating.j.JRating jRatingPuntuar;
    // End of variables declaration//GEN-END:variables
}
