
package GUI;

import javax.swing.JSlider;
 import java.sql.Date;
import javax.swing.JLabel;
import javax.swing.SwingConstants;

/**
 *
 * @author alumnogreibd
 */
public class E1_Puntuar extends javax.swing.JFrame {
    private proyectobasesdatos.ProyectoBasesDatos pr;
    private E1 padre;
    private Date fecha;
    private String dni;
    private String nombreEstablecimiento;

    /**
     * Creates new form E1_Puntuar
     */
    public E1_Puntuar(proyectobasesdatos.ProyectoBasesDatos pr, E1 padre, Date fecha, String dni, String nombreEstablecimiento) {
        this.pr = pr;
        this.padre = padre;
        this.fecha = fecha;
        this.dni = dni;
        this.nombreEstablecimiento = nombreEstablecimiento;
        initComponents();
        //JLabel Titulo2 = new JLabel("Valore la experiencia en " + nombreEstablecimiento + " en la fecha " + fecha.toString(), SwingConstants.CENTER);
        Titulo.setText("Valore la experiencia en " + nombreEstablecimiento + " en la fecha " + fecha.toString());
        Titulo.setHorizontalAlignment(SwingConstants.CENTER);
        Titulo.setVerticalAlignment(SwingConstants.CENTER);
        jSliderPuntuar.setValueIsAdjusting(true);
        jSliderPuntuar.setMajorTickSpacing(1);
        jSliderPuntuar.setPaintTicks(true);
        jSliderPuntuar.setPaintLabels(true);
        jSliderPuntuar.setExtent(1);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jSliderPuntuar = new JSlider(0, 10, 10);
        Puntuar = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Puntuar.setText("Puntuar");
        Puntuar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PuntuarActionPerformed(evt);
            }
        });

        Titulo.setText("Titulo (dinámico)");

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addComponent(Atras)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Puntuar)
                .addGap(86, 86, 86))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jSliderPuntuar, javax.swing.GroupLayout.PREFERRED_SIZE, 343, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(126, 126, 126)
                        .addComponent(Titulo)))
                .addContainerGap(191, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(102, 102, 102)
                .addComponent(Titulo)
                .addGap(100, 100, 100)
                .addComponent(jSliderPuntuar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 141, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Puntuar)
                    .addComponent(Atras))
                .addGap(44, 44, 44))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void PuntuarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PuntuarActionPerformed
                
        pr.getComerDAO().puntuar(fecha, dni, nombreEstablecimiento, jSliderPuntuar.getValue());
        padre.buscarEvaluacionesPendientes(); //Actualizo para que ya no aparezca la comida actual como pendiente de evaluar
        this.setVisible(false);
        padre.setVisible(true);

    }//GEN-LAST:event_PuntuarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Puntuar;
    private javax.swing.JLabel Titulo;
    private javax.swing.JSlider jSliderPuntuar;
    // End of variables declaration//GEN-END:variables
}
