/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alumnogreibd
 */
public class EspectaculomasPopularAño extends javax.swing.JFrame {
    private proyectobasesdatos.ProyectoBasesDatos pr;
    private MenuBusquedas padre;
    /**
     * Creates new form EspectaculomasPopularAño
     */

    
    public EspectaculomasPopularAño(proyectobasesdatos.ProyectoBasesDatos pr, MenuBusquedas padre) {
        this.pr = pr;
        this.padre=padre;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Titulo = new javax.swing.JLabel();
        Anho = new javax.swing.JLabel();
        String [] array = pr.getEspectaculosDAO().añosRegistrados().toArray(new String[pr.getEspectaculosDAO().añosRegistrados().size()]);
        jComboBoxAnhos = new javax.swing.JComboBox<>();
        Atras = new javax.swing.JButton();
        jScrollPaneResultados = new javax.swing.JScrollPane();
        tablaEspectaculo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        Titulo.setText("Espectáculo Más Popular por Año");

        Anho.setText("Año");

        jComboBoxAnhos.setModel(new javax.swing.DefaultComboBoxModel<>(array));
        jComboBoxAnhos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxAnhosActionPerformed(evt);
            }
        });

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        tablaEspectaculo.setModel(new ModeloTablaAsistir());
        jScrollPaneResultados.setViewportView(tablaEspectaculo);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addComponent(Titulo)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(Anho)
                                .addGap(30, 30, 30)
                                .addComponent(jComboBoxAnhos, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(134, 134, 134)
                                .addComponent(Atras))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jScrollPaneResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Titulo)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Anho)
                    .addComponent(jComboBoxAnhos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPaneResultados, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(Atras)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxAnhosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxAnhosActionPerformed
        consultarEspectaculo();
    }//GEN-LAST:event_jComboBoxAnhosActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
       this.setVisible(false);
       padre.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed



    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Anho;
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Titulo;
    private javax.swing.JComboBox<String> jComboBoxAnhos;
    private javax.swing.JScrollPane jScrollPaneResultados;
    private javax.swing.JTable tablaEspectaculo;
    // End of variables declaration//GEN-END:variables
    
    public void consultarEspectaculo() {
        ModeloTablaAsistir m;
        String anho;
        anho = (String)jComboBoxAnhos.getSelectedItem();        
        m = (ModeloTablaAsistir) tablaEspectaculo.getModel();     
        m.setFilas(pr.getEspectaculosDAO().espectaculoMasPopularPorAnho(anho));
    }



}
