/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alumnogreibd
 */
public class MenuCancelaciones extends javax.swing.JFrame {
    private proyectobasesdatos.ProyectoBasesDatos pr;
    private MenuUsuarios padre;
    private String dni;
    
    public MenuCancelaciones(proyectobasesdatos.ProyectoBasesDatos pr, MenuUsuarios padre, String dni) {
        this.pr = pr;
        this.padre = padre;
        this.dni = dni;
        initComponents();
    }
    /**
     * Creates new form CancelarEntradas
     */
    public MenuCancelaciones() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cancelarentradaatraccion = new javax.swing.JButton();
        Cancelarentradaespectaculo = new javax.swing.JButton();
        cancelarRestaurante = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cancelarentradaatraccion.setBorderPainted(false);
        cancelarentradaatraccion.setContentAreaFilled(false);
        cancelarentradaatraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarentradaatraccionActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarentradaatraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 160, 320, 50));

        Cancelarentradaespectaculo.setBorderPainted(false);
        Cancelarentradaespectaculo.setContentAreaFilled(false);
        Cancelarentradaespectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarentradaespectaculoActionPerformed(evt);
            }
        });
        jPanel1.add(Cancelarentradaespectaculo, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 230, 320, 50));

        cancelarRestaurante.setBorderPainted(false);
        cancelarRestaurante.setContentAreaFilled(false);
        cancelarRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelarRestauranteActionPerformed(evt);
            }
        });
        jPanel1.add(cancelarRestaurante, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 300, 320, 50));

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 400, 80, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Cancelaciones.jpeg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 800, 450));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    private void cancelarRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarRestauranteActionPerformed
       CancelarReservaRestaurante Crr= new CancelarReservaRestaurante(pr, this, dni);
        this.setVisible(false);
        Crr.setVisible(true);
       
    }//GEN-LAST:event_cancelarRestauranteActionPerformed

    private void CancelarentradaespectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarentradaespectaculoActionPerformed
        CancelarEntradaEspectaculo cr= new CancelarEntradaEspectaculo(pr, this, dni);
        this.setVisible(false);
        cr.setVisible(true);    }//GEN-LAST:event_CancelarentradaespectaculoActionPerformed

    private void cancelarentradaatraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelarentradaatraccionActionPerformed
        CancelarEntradaAtraccion cr= new CancelarEntradaAtraccion(pr, this, dni);
        this.setVisible(false);
        cr.setVisible(true);
    }//GEN-LAST:event_cancelarentradaatraccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuCancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuCancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuCancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuCancelaciones.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuCancelaciones().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelarentradaespectaculo;
    private javax.swing.JButton atras;
    private javax.swing.JButton cancelarRestaurante;
    private javax.swing.JButton cancelarentradaatraccion;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
