/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author alumnogreibd
 */
public class MenuAdministradores extends javax.swing.JFrame {
    private MenuInicio padre;
    private proyectobasesdatos.ProyectoBasesDatos pr;
    private String dni;
   // private Inicio padre;
    
    /**
     *
     */
    public MenuAdministradores() {
        initComponents();
    }

    /**
     *
     * @param pr
     */
    public MenuAdministradores(proyectobasesdatos.ProyectoBasesDatos pr, MenuInicio padre) {
        this.pr = pr;
        this.padre=padre;
        initComponents();
    }


      

      public MenuAdministradores(proyectobasesdatos.ProyectoBasesDatos pr, String dni) {
        this.pr = pr;
        this.dni=dni;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        Salir = new javax.swing.JButton();
        Beneficios = new javax.swing.JButton();
        regalarEntradas = new javax.swing.JButton();
        trabajadores = new javax.swing.JButton();
        GestionFalloAtraccion = new javax.swing.JButton();
        Atras = new javax.swing.JButton();
        MenuAdministradores = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel1.add(jLayeredPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 300, -1, -1));

        Salir.setBorderPainted(false);
        Salir.setContentAreaFilled(false);
        Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalirActionPerformed(evt);
            }
        });
        jPanel1.add(Salir, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 70, 30));

        Beneficios.setBorderPainted(false);
        Beneficios.setContentAreaFilled(false);
        Beneficios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BeneficiosActionPerformed(evt);
            }
        });
        jPanel1.add(Beneficios, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 200, 60));

        regalarEntradas.setBorderPainted(false);
        regalarEntradas.setContentAreaFilled(false);
        regalarEntradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                regalarEntradasActionPerformed(evt);
            }
        });
        jPanel1.add(regalarEntradas, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 260, 120, 70));

        trabajadores.setBorderPainted(false);
        trabajadores.setContentAreaFilled(false);
        trabajadores.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabajadoresActionPerformed(evt);
            }
        });
        jPanel1.add(trabajadores, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 260, 130, 70));

        GestionFalloAtraccion.setBorderPainted(false);
        GestionFalloAtraccion.setContentAreaFilled(false);
        GestionFalloAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GestionFalloAtraccionActionPerformed(evt);
            }
        });
        jPanel1.add(GestionFalloAtraccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 150, 70));

        Atras.setBorderPainted(false);
        Atras.setContentAreaFilled(false);
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });
        jPanel1.add(Atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 410, 70, 30));

        MenuAdministradores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuAdministradores.jpeg"))); // NOI18N
        jPanel1.add(MenuAdministradores, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 810, 460));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void regalarEntradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_regalarEntradasActionPerformed
        RegalarEntradas r= new RegalarEntradas(pr, this);
        this.setVisible(false);
        r.setVisible(true);
    }//GEN-LAST:event_regalarEntradasActionPerformed

    private void BeneficiosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BeneficiosActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        BeneficiosAtracciones ba = new BeneficiosAtracciones(pr,this);
        ba.setVisible(true);

    }//GEN-LAST:event_BeneficiosActionPerformed

    private void SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalirActionPerformed
        // TODO add your handling code here:
        System.exit(0);
        try {
            pr.getConexion().close();
        } catch (SQLException ex) {
            Logger.getLogger(MenuAdministradores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_SalirActionPerformed

    private void trabajadoresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabajadoresActionPerformed
        MenuEmpleados me=new MenuEmpleados(pr, this);
        this.setVisible(false);
        me.setVisible(true);
    }//GEN-LAST:event_trabajadoresActionPerformed

    private void GestionFalloAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GestionFalloAtraccionActionPerformed
        GestionarFalloAtraccion gfa= new GestionarFalloAtraccion(pr,this);
        this.setVisible(false);
        gfa.setVisible(true);
    }//GEN-LAST:event_GestionFalloAtraccionActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdministradores.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdministradores().setVisible(true);
            }
        });        
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton Beneficios;
    private javax.swing.JButton GestionFalloAtraccion;
    private javax.swing.JLabel MenuAdministradores;
    private javax.swing.JButton Salir;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton regalarEntradas;
    private javax.swing.JButton trabajadores;
    // End of variables declaration//GEN-END:variables
}
