/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alumnogreibd
 */
public class MenuEmpleados extends javax.swing.JFrame {

    private proyectobasesdatos.ProyectoBasesDatos pr;
    private MenuAdministradores padre;

   

    public MenuEmpleados(proyectobasesdatos.ProyectoBasesDatos pr,MenuAdministradores padre) {
        initComponents();
        this.padre=padre;
        this.pr=pr;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        trabAtra = new javax.swing.JButton();
        trabEsp = new javax.swing.JButton();
        hosteleros = new javax.swing.JButton();
        despedir = new javax.swing.JButton();
        contratar = new javax.swing.JButton();
        atras = new javax.swing.JButton();
        MenuEmpleados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        trabAtra.setBorderPainted(false);
        trabAtra.setContentAreaFilled(false);
        trabAtra.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabAtraActionPerformed(evt);
            }
        });
        jPanel1.add(trabAtra, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 250, 190, 20));

        trabEsp.setBorderPainted(false);
        trabEsp.setContentAreaFilled(false);
        trabEsp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                trabEspActionPerformed(evt);
            }
        });
        jPanel1.add(trabEsp, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 273, 200, 20));

        hosteleros.setBorderPainted(false);
        hosteleros.setContentAreaFilled(false);
        hosteleros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hostelerosActionPerformed(evt);
            }
        });
        jPanel1.add(hosteleros, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 90, 20));

        despedir.setBorderPainted(false);
        despedir.setContentAreaFilled(false);
        despedir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                despedirActionPerformed(evt);
            }
        });
        jPanel1.add(despedir, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 230, 80));

        contratar.setBorderPainted(false);
        contratar.setContentAreaFilled(false);
        contratar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                contratarActionPerformed(evt);
            }
        });
        jPanel1.add(contratar, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 230, 70));

        atras.setBorderPainted(false);
        atras.setContentAreaFilled(false);
        atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                atrasActionPerformed(evt);
            }
        });
        jPanel1.add(atras, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 410, 60, 30));

        MenuEmpleados.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/MenuEmpleados.jpeg"))); // NOI18N
        jPanel1.add(MenuEmpleados, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void contratarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_contratarActionPerformed
        this.setVisible(false);
        AnhadirEmpleados e = new AnhadirEmpleados(pr, this);
        e.setVisible(true);
    }//GEN-LAST:event_contratarActionPerformed

    private void despedirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_despedirActionPerformed
        this.setVisible(false);
        DespedirEmpleados de = new DespedirEmpleados(pr, this);
        de.setVisible(true);
    }//GEN-LAST:event_despedirActionPerformed

    private void trabAtraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabAtraActionPerformed
        TablaTrabajAtracc ta = new TablaTrabajAtracc(pr,this);
        this.setVisible(false);
        ta.setVisible(true);
    }//GEN-LAST:event_trabAtraActionPerformed

    private void trabEspActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_trabEspActionPerformed
        TablaTrabajEspec ta = new TablaTrabajEspec(pr,this);
        this.setVisible(false);
        ta.setVisible(true);    }//GEN-LAST:event_trabEspActionPerformed

    private void hostelerosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hostelerosActionPerformed
        TablaHosteleros ta = new TablaHosteleros(pr,this);
        this.setVisible(false);
        ta.setVisible(true);
    }//GEN-LAST:event_hostelerosActionPerformed

    private void atrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_atrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_atrasActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel MenuEmpleados;
    private javax.swing.JButton atras;
    private javax.swing.JButton contratar;
    private javax.swing.JButton despedir;
    private javax.swing.JButton hosteleros;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton trabAtra;
    private javax.swing.JButton trabEsp;
    // End of variables declaration//GEN-END:variables
}
