/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

/**
 *
 * @author alumnogreibd
 */
public class MenuComprasReservas extends javax.swing.JFrame {
    private proyectobasesdatos.ProyectoBasesDatos pr;
    private MenuUsuarios padre;
    private String dni;
    
    public MenuComprasReservas(proyectobasesdatos.ProyectoBasesDatos pr, MenuUsuarios padre, String dni) {
        this.pr = pr;
        this.padre = padre;
        this.dni = dni;
        initComponents();
    }
    /**
     * Creates new form ComprarReservarEntrada
     */
    public MenuComprasReservas() {
        initComponents();
    }
 
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bienvenido = new javax.swing.JLabel();

        Atras = new javax.swing.JButton();
        ComprarEntradasEspectaculo = new javax.swing.JButton();
        ReservarEnRestaurante = new javax.swing.JButton();
        ComprarEntradaAtraccion = new javax.swing.JButton();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bienvenido.setText("Compras y Reservas");

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        ComprarEntradasEspectaculo.setText("Comprar Entradas Espectáculo");
        ComprarEntradasEspectaculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarEntradasEspectaculoActionPerformed(evt);
            }
        });

        ReservarEnRestaurante.setText("Reservar en Restaurante");
        ReservarEnRestaurante.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReservarEnRestauranteActionPerformed(evt);

            }
        });

        ComprarEntradaAtraccion.setText("Comprar Entradas Atracción");
        ComprarEntradaAtraccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ComprarEntradaAtraccionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()


                        .addGap(133, 133, 133)
                        .addComponent(bienvenido))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(ReservarEnRestaurante)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ComprarEntradaAtraccion)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(ComprarEntradasEspectaculo)
                            .addGap(85, 85, 85))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addComponent(Atras)
                            .addGap(161, 161, 161)))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(bienvenido)
                .addGap(29, 29, 29)

                .addComponent(ComprarEntradaAtraccion)
                .addGap(39, 39, 39)
                .addComponent(ComprarEntradasEspectaculo)

                .addGap(32, 32, 32)
                .addComponent(ReservarEnRestaurante)
                .addGap(26, 26, 26)
                .addComponent(Atras)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);

        
    }//GEN-LAST:event_AtrasActionPerformed

    private void ComprarEntradasEspectaculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarEntradasEspectaculoActionPerformed
        ComprarEntradaEspectaculo Cee = new ComprarEntradaEspectaculo(pr, this, dni);
        this.setVisible(false);
        Cee.setVisible(true);
    }//GEN-LAST:event_ComprarEntradasEspectaculoActionPerformed

    private void ReservarEnRestauranteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReservarEnRestauranteActionPerformed
        ReservarEnRestaurante Rer = new ReservarEnRestaurante(pr, this, dni);
        this.setVisible(false);
        Rer.setVisible(true);
    }//GEN-LAST:event_ReservarEnRestauranteActionPerformed


    private void ComprarEntradaAtraccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ComprarEntradaAtraccionActionPerformed
        ComprarEntradasAtracciones Cea = new ComprarEntradasAtracciones(pr, this, dni);
        this.setVisible(false);
        Cea.setVisible(true);
    }//GEN-LAST:event_ComprarEntradaAtraccionActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuComprasReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuComprasReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuComprasReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuComprasReservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuComprasReservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JButton ComprarEntradaAtraccion;
    private javax.swing.JButton ComprarEntradasEspectaculo;
    private javax.swing.JButton ReservarEnRestaurante;
    private javax.swing.JLabel bienvenido;

    // End of variables declaration//GEN-END:variables
}
