/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author alumnogreibd
 */
public class RegalarEntradas extends javax.swing.JFrame {

    private proyectobasesdatos.ProyectoBasesDatos pr;
    private MenuAdministradores padre;
    //private String dni;

    public RegalarEntradas(proyectobasesdatos.ProyectoBasesDatos pr, MenuAdministradores padre) {
        this.pr = pr;
        this.padre = padre;
        //this.dni = dni;
        initComponents();
    }

    /**
     * Creates new form regalarEntradas
     */
    public RegalarEntradas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        IntroducirLimite = new javax.swing.JTextField();
        SeleccionarTodoTabla = new javax.swing.JButton();
        Regalar = new javax.swing.JButton();
        Info2 = new javax.swing.JLabel();
        Atras = new javax.swing.JButton();
        InfoButtonSeleccionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        TablaVisitantesResumen = new javax.swing.JTable();
        InformacionButton = new javax.swing.JButton();
        Titulo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        IntroducirLimite.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IntroducirLimiteActionPerformed(evt);
            }
        });

        SeleccionarTodoTabla.setText("Seleccionar todo");
        SeleccionarTodoTabla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SeleccionarTodoTablaActionPerformed(evt);
            }
        });

        Regalar.setText("Regalar a seleccionados ");
        Regalar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegalarActionPerformed(evt);
            }
        });

        Info2.setFont(new java.awt.Font("sansserif", 0, 10)); // NOI18N

        Atras.setText("Atrás");
        Atras.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AtrasActionPerformed(evt);
            }
        });

        InfoButtonSeleccionar.setText("Ayuda para seleccionar");
        InfoButtonSeleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InfoButtonSeleccionarActionPerformed(evt);
            }
        });

        TablaVisitantesResumen.setModel(new ModeloTablaVisitanteResumen());
        jScrollPane2.setViewportView(TablaVisitantesResumen);

        InformacionButton.setText("Información");
        InformacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InformacionButtonActionPerformed(evt);
            }
        });

        Titulo.setFont(new java.awt.Font("C059", 2, 24)); // NOI18N
        Titulo.setText("Regalar Entradas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(Atras)
                        .addGap(142, 142, 142)
                        .addComponent(Regalar)
                        .addGap(100, 100, 100))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 631, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(SeleccionarTodoTabla)
                    .addComponent(InfoButtonSeleccionar))
                .addGap(0, 17, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(136, 136, 136)
                        .addComponent(Info2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(IntroducirLimite, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(174, 174, 174)
                        .addComponent(InformacionButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(300, 300, 300)
                        .addComponent(Titulo)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(Titulo)
                .addGap(18, 18, 18)
                .addComponent(Info2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IntroducirLimite, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(InformacionButton))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(InfoButtonSeleccionar)
                        .addGap(444, 444, 444)
                        .addComponent(SeleccionarTodoTabla))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 490, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Regalar)
                    .addComponent(Atras))
                .addGap(36, 36, 36))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void IntroducirLimiteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IntroducirLimiteActionPerformed
        buscarMasGastadores(IntroducirLimite.getText());
    }//GEN-LAST:event_IntroducirLimiteActionPerformed

    private void RegalarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegalarActionPerformed

        int[] filasSeleccionadas;

        if (TablaVisitantesResumen.getRowCount() > 0) {
            if (TablaVisitantesResumen.getSelectedRowCount() > 0) {
                filasSeleccionadas = TablaVisitantesResumen.getSelectedRows(); //Así consigo los índices de las seleccionadas
                for (int i : filasSeleccionadas) {
                    pr.getIrDAO().regalarEntrada(TablaVisitantesResumen.getValueAt(i, 0).toString()); //Envío el DNI para regalar
                }
                JOptionPane.showMessageDialog(rootPane, "Entradas regaladas a " + filasSeleccionadas.length + " persona/s");
                this.setVisible(false);
                padre.setVisible(true);
            }
        }
    }//GEN-LAST:event_RegalarActionPerformed

    private void SeleccionarTodoTablaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SeleccionarTodoTablaActionPerformed
        TablaVisitantesResumen.selectAll();
    }//GEN-LAST:event_SeleccionarTodoTablaActionPerformed

    private void InfoButtonSeleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InfoButtonSeleccionarActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Para seleccionar filas debe clicar en ellas\nPuede seleccionar un conjunto de filas contiguas clicando y arrastrando\nPara seleccionar filas no contiguas use crtl+click");
    }//GEN-LAST:event_InfoButtonSeleccionarActionPerformed

    private void AtrasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AtrasActionPerformed
        this.setVisible(false);
        padre.setVisible(true);
    }//GEN-LAST:event_AtrasActionPerformed

    private void InformacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InformacionButtonActionPerformed
        JOptionPane.showMessageDialog(rootPane, "Desde aquí puede regalar entradas de atracciones a los visitantes teniendo como información el dinero que han gastado. Pasos a seguir: "
                + "\n\n 1.- Introduzca en el cuadro de texto el número de usuarios con mayor gasto que quiere que se muestren y pulse INTRO"
                + "\n\n 2.- Seleccione a los visitantes que quiera regalarles una entrada (será para el día siguiente al actual y para su atracción favorita)"
                + "\n\n 3.- Pulse Regalar a seleccionados para finalizar esta operación"
        );
    }//GEN-LAST:event_InformacionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RegalarEntradas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RegalarEntradas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RegalarEntradas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RegalarEntradas.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RegalarEntradas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Atras;
    private javax.swing.JLabel Info2;
    private javax.swing.JButton InfoButtonSeleccionar;
    private javax.swing.JButton InformacionButton;
    private javax.swing.JTextField IntroducirLimite;
    private javax.swing.JButton Regalar;
    private javax.swing.JButton SeleccionarTodoTabla;
    private javax.swing.JTable TablaVisitantesResumen;
    private javax.swing.JLabel Titulo;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables

    public void buscarMasGastadores(String limite) {

        ModeloTablaVisitanteResumen m;
        Integer limit = 10000; //Si el campo esta vacio, ponemos un limite alto

        if (!IntroducirLimite.getText().isBlank()) {
            if (isInteger(IntroducirLimite.getText())) {    //Si no se pudiera transformar a entero, muestra los 10000
                limit = Integer.parseInt(limite);
            }
        }
        m = (ModeloTablaVisitanteResumen) TablaVisitantesResumen.getModel();
        m.setFilas(pr.getVisitantesDAO().listarPersonasConMasGasto(limit));

        if (m.getRowCount() > 0) {
            TablaVisitantesResumen.setRowSelectionInterval(0, 0);
        }
    }

//Función para saber si el dato introducido se puede pasar a Integer (código proveniente de stackoverflow)
    public boolean isInteger(String str) {
        if (str == null) {
            return false;
        }
        int length = str.length();
        if (length == 0) {
            return false;
        }
        int i = 0;
        if (str.charAt(0) == '-') {
            if (length == 1) {
                return false;
            }
            i = 1;
        }
        for (; i < length; i++) {
            char c = str.charAt(i);
            if (c < '0' || c > '9') {
                return false;
            }
        }
        return true;
    }

}
